/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnector;
import config.passwordhasher;
import inventory.loginForm;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.userdashboard;

/**
 *
 * @author SCC-COLLEGE
 */
public class changepass extends javax.swing.JFrame {

    /**
     * Creates new form changepass
     */
    public changepass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        u_id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        oldpass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        conpass = new javax.swing.JPasswordField();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel14.setBackground(new java.awt.Color(0, 153, 102));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Change Pass");
        jPanel14.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, 170, 40));

        jPanel15.setBackground(new java.awt.Color(153, 255, 153));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(102, 255, 102));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 270, -1));

        jLabel11.setText("Currently user");
        jPanel15.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, 30));

        u_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        u_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u_id.setText("ID");
        jPanel15.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 50, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 70, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Id");
        jPanel15.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 60, 50, -1));

        id.setEnabled(false);
        jPanel15.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 57, 100, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("old pass");
        jPanel15.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("new pass");
        jPanel15.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 50, -1));
        jPanel15.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, -1));
        jPanel15.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, -1));

        jLabel2.setText("confirm pass");
        jPanel15.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));
        jPanel15.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel15.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        userdashboard ud = new userdashboard();
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try{
           dbConnector dbc = new dbConnector();
           Session sess = Session.getInstance();
           
           String query = "SELECT * FROM tbl_user WHERE u_id= '"+sess.getUid()+"'";
           ResultSet rs = dbc.getData(query);
           
           if(rs.next()){
               String olddbpass = rs.getString("u_password");
               String oldhash = passwordhasher.hashPassword(oldpass.getText());
               
               if(!olddbpass.equals(oldhash)){
                    JOptionPane.showMessageDialog(null, "Old Password is Incorrect!");
                    oldpass.setText("");
               }else if(newpass.getText().length() < 8){
                    JOptionPane.showMessageDialog(null, "Password must be 8 characters and above!");
                    newpass.setText("");
                }else if(!newpass.getText().equals(conpass.getText())){
                    JOptionPane.showMessageDialog(null, "Confirm Password does not Match!");
                    conpass.setText("");
                }else{
                    String npass = passwordhasher.hashPassword(newpass.getText());
                    dbc.updateData("UPDATE tbl_user SET u_password = '"+npass+"' WHERE u_id = '"+sess.getUid()+"'");
                    JOptionPane.showMessageDialog(null, "Password Changed Successfully!");
                    loginForm lf = new loginForm();
                    lf.setVisible(true);
                    this.dispose();
               }
           }
                   
                   
       }catch(SQLException | NoSuchAlgorithmException ex){
           System.out.println(""+ex);
       }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPasswordField conpass;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    public javax.swing.JPasswordField newpass;
    public javax.swing.JPasswordField oldpass;
    private javax.swing.JButton save;
    private javax.swing.JLabel u_id;
    // End of variables declaration//GEN-END:variables
}
