/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-COLLEGE
 */
public class createUserform extends javax.swing.JFrame {

    /**
     * Creates new form createUserform
     */
    public createUserform() {
        initComponents();
        displayData();
    }
     public static String uemail,uname;
     public boolean duplicateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{ 
             String query = "SELECT * FROM tbl_user  WHERE u_username = '" + un.getText() + "' OR u_email = '" + em.getText() + "'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                
                uemail = resultSet.getString("u_email");
                
                if(uemail.equals(em.getText())){
                    JOptionPane.showMessageDialog(null,"Email is already use !");
                    em.setText("");
                }
                
                uname = resultSet.getString("u_username");
                
                if(uname.equals(un.getText())){
                    
                    JOptionPane.showMessageDialog(null,"Username is already use !");
                    un.setText("");
                }
                return true;
            }else{
                return false;
            }
       
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
            
             
            
        }
    }
      public boolean updateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{ 
             String query = "SELECT * FROM tbl_user  WHERE (u_username = '" + un.getText() + "' OR u_email = '" + em.getText() + "')AND u_id !='"+uid.getText()+"' ";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                
                uemail = resultSet.getString("u_email");
                
                if(uemail.equals(em.getText())){
                    JOptionPane.showMessageDialog(null,"Email is already use !");
                    em.setText("");
                }
                
                uname = resultSet.getString("u_username");
                
                if(uname.equals(un.getText())){
                    
                    JOptionPane.showMessageDialog(null,"Username is already use !");
                    un.setText("");
                }
                return true;
            }else{
                return false;
            }
       
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
            
             
            
        }
    }
    
     public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT u_id,u_fname,u_email,u_type,u_status FROM tbl_user");
            userTables.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
        
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTables = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ust = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ps = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        u_id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(153, 255, 153));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTablesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTables);

        jPanel15.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 330, 270));

        jPanel16.setBackground(new java.awt.Color(102, 255, 102));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Id");
        jPanel16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 60, 50, -1));

        jLabel12.setText("First Name");
        jPanel16.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 103, -1, -1));

        jLabel13.setText("Last Name");
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel14.setText("Email");
        jPanel16.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 201, -1, -1));

        jLabel16.setText("Username");
        jPanel16.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 253, -1, -1));
        jPanel16.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 57, 100, -1));
        jPanel16.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 100, 100, -1));
        jPanel16.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 145, 100, -1));
        jPanel16.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 198, 100, -1));
        jPanel16.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 250, 100, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 270, -1));

        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel17.setText("user status");
        jPanel15.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        ust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        jPanel15.add(ust, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        add.setText("ADD");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel15.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        jLabel15.setText("user type");
        jPanel15.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel15.add(ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel18.setText("Password");
        jPanel15.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 30));
        jPanel15.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, 30));

        jLabel11.setText("Currently user");
        jPanel15.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 360, 90, 30));

        u_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u_id.setText("id");
        jPanel15.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 50, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cancel");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 50, -1));

        update.setText("Upadate");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel15.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Back)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTablesMouseClicked
        int rowIndex = userTables.getSelectedRow();

        TableModel model = userTables.getModel();
        String id  = model.getValueAt(rowIndex,0).toString();

        dbConnector dbc = new dbConnector();
        try{
            ResultSet rs = dbc.getData("SELECT * FROM tbl_user  WHERE u_id = '" + id + "'");
            if(rs.next()){
                uid.setText(rs.getString("u_id"));
                fn.setText(rs.getString("u_fname"));
                ln.setText(rs.getString("u_lname"));
                em.setText(rs.getString("u_email"));
                un.setText(rs.getString("u_username"));
                ps.setText(rs.getString("u_password"));
                ut.setSelectedItem(rs.getString("u_type"));
                ust.setSelectedItem(rs.getString("u_status"));

            }

        }catch(SQLException ex){
            System.out.println(""+ex);
        }

    }//GEN-LAST:event_userTablesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if(fn.getText().isEmpty() || ln.getText().isEmpty()||em.getText().isEmpty()||un.getText().isEmpty()
            ||ps.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All fields are required!");

        }else if(ps.getText().length()<8){
            JOptionPane.showMessageDialog(null,"Password should be above 8!");
            ps.setText("");
        }else if(duplicateCheck()){
            System.out.println("Duplicate Exist");
        }
        else{

            dbConnector dbc = new dbConnector();
            if(dbc.insertData("INSERT INTO tbl_user"
                +"(u_fname,u_lname,u_email,u_username,u_password,u_type,u_status)"
                + "VALUES('"+fn.getText()+"','"+ln.getText()+"','"+em.getText()+"',"
                + "'"+un.getText()+"','"+ps.getText()+"','"+ut.getSelectedItem()+"','"+ust.getSelectedItem()+"') ")){

            JOptionPane.showMessageDialog(null,"inserted successfully");

            displayData();
            fn.setText("");

        }else{
            JOptionPane.showMessageDialog(null,"inserted error");
        }
        }
    }//GEN-LAST:event_addActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        admindashboard ad = new admindashboard();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sees = Session.getInstance();
       u_id.setText(""+sees.getUid());
    }//GEN-LAST:event_formWindowActivated

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        userform us = new userform();
        us.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        
         if(fn.getText().isEmpty() || ln.getText().isEmpty()||em.getText().isEmpty()||un.getText().isEmpty()
            ||ps.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All fields are required!");

        }else if(ps.getText().length()<8){
            JOptionPane.showMessageDialog(null,"Password should be above 8!");
            ps.setText("");
        }else if(updateCheck()){
            System.out.println("Duplicate Exist");
        }
        else{
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_user SET u_fname ='"+fn.getText()+"',u_lname = '"+ln.getText()+"',u_email ='"+em.getText()+"',u_username ='"+un.getText()+"',u_password ='"+ps.getText()+"',"
                + "u_type ='"+ut.getSelectedItem()+"',u_status = '"+ust.getSelectedItem()+"'WHERE u_id = '"+uid.getText()+"' ");
        }
        
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createUserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createUserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createUserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createUserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createUserform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    public javax.swing.JButton add;
    public javax.swing.JTextField em;
    public javax.swing.JTextField fn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField ln;
    public javax.swing.JTextField ps;
    private javax.swing.JLabel u_id;
    public javax.swing.JTextField uid;
    public javax.swing.JTextField un;
    private javax.swing.JButton update;
    private javax.swing.JTable userTables;
    public javax.swing.JComboBox<String> ust;
    public javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
